[package]
name = "rim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anes = "0.1.6"
term_size = "0.3.2"
win32console = "0.1.5"
winapi = "0.3.9"
